import Head from "next/head";
import { Roboto_Slab } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner/banner";
import Navbar from "@/components/navbar/navbar";
import Card from "@/components/card/card";
import SectionCards from "@/components/card/section-cards";
import {
  getVideos,
  getPopularVideos,
  getWatchItAgainVideos,
} from "@/lib/videos";
import { verifyToken } from "@/lib/utils";
import { redirectUser } from "@/utils/redirectUser";

const robotoSlab = Roboto_Slab({
  display: "swap",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-roboto",
});

export async function getServerSideProps(context) {
  const { userId, token } = await redirectUser(context);
  console.log({ userId, token });
  if (!userId) {
    return {
      props: {},
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  const watchItAgainVideos = await getWatchItAgainVideos(userId, token);
  console.log({ watchItAgainVideos });
  const duneVideos = await getVideos("dune part two");
  // const travelVideos = await getVideos("travel europe");
  // const productivityVideos = await getVideos("Productivity");
  // const popularVideos = await getPopularVideos();
  // const duneVideos = [];
  const travelVideos = [];
  const productivityVideos = [];
  const popularVideos = [];
  return {
    props: {
      duneVideos,
      travelVideos,
      popularVideos,
      productivityVideos,
      watchItAgainVideos,
    },
  };
}

export default function Home({
  duneVideos,
  travelVideos,
  popularVideos,
  productivityVideos,
  watchItAgainVideos = [],
}) {
  // console.log({ magic });
  // startFetchMyQuery();
  return (
    <div styles={styles.container} className={robotoSlab.className}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <Navbar username={"Dani"} />
        <Banner
          videoId="U2Qp5pL3ovA"
          title="Dune: Part Two"
          subtitle="The next chapter"
          imgUrl="/static/dune-part-two.jpg"
        />
        <div className={styles.sectionWrapper}>
          <SectionCards title="Dune" videos={duneVideos} size="large" />
          <SectionCards
            title="Watch It Again"
            videos={watchItAgainVideos}
            size="small"
          />
          <SectionCards title="Travel" videos={travelVideos} size="small" />
          <SectionCards
            title="Productivity"
            videos={productivityVideos}
            size="medium"
          />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
        </div>
      </div>
    </div>
  );
}
